# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Integration Test"

on:
  pull_request:
  push:
    branches:
      - "0.x"

jobs:
  test:
    name: "Integration Test"
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-version:
          #- "7.2"
          #- "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
        dependencies:
          - "lowest"
          - "highest"
        script:
          - "make lint"
          - "make phpstan"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Checkout phpstan-src"
        uses: actions/checkout@v4
        with:
          repository: phpstan/phpstan-src
          path: phpstan-src

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=512M

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"

      - name: "Install phpstan-src dependencies"
        working-directory: "phpstan-src"
        run: "composer install"

      - name: "Downgrade code"
        working-directory: "phpstan-src"
        shell: bash
        run: "../bin/simple-downgrade downgrade -c build/downgrade.php ${{ matrix.php-version }}"

      - name: "Script"
        working-directory: "phpstan-src"
        shell: bash
        run: "${{ matrix.script }}"
